Wagtail 6.1
torchbox-forks/wagtail-django-recaptcha pull request #17
Opened 2024-05-16 08:42 UTC by katdom13

# Notes

- No significant changes related to Wagtail 6.1

# Wagtail 6.1 upgrade check list

## Code reviewing a consideration.
Use the tick box to indicate a consideration has been code reviewed as OK

### What’s new
  - [ ] [Universal listings continued](https://docs.wagtail.org/en/latest/releases/6.1.html#universal-listings-continued)
  - [ ] [Information-dense admin interface](https://docs.wagtail.org/en/latest/releases/6.1.html#information-dense-admin-interface)
  - [ ] [Custom per-page-type listings](https://docs.wagtail.org/en/latest/releases/6.1.html#custom-per-page-type-listings)
  - [ ] [Keyboard shortcuts overview](https://docs.wagtail.org/en/latest/releases/6.1.html#keyboard-shortcuts-overview)
  - [ ] [Better guidance for password-protected content](https://docs.wagtail.org/en/latest/releases/6.1.html#better-guidance-for-password-protected-content)
  - [ ] [Favicon images generation](https://docs.wagtail.org/en/latest/releases/6.1.html#favicon-images-generation)
  - [ ] [Cve-2024-32882: permission check bypass when editing a model with per-field restrictions through wagtail.contrib.settings or modelviewset](https://docs.wagtail.org/en/latest/releases/6.1.html#cve-2024-32882-permission-check-bypass-when-editing-a-model-with-per-field-restrictions-through-wagtail-contrib-settings-or-modelviewset)
  - [ ] [Other features](https://docs.wagtail.org/en/latest/releases/6.1.html#other-features)
  - [ ] [Bug fixes](https://docs.wagtail.org/en/latest/releases/6.1.html#bug-fixes)
  - [ ] [Documentation](https://docs.wagtail.org/en/latest/releases/6.1.html#documentation)
  - [ ] [Maintenance](https://docs.wagtail.org/en/latest/releases/6.1.html#maintenance)
### Changes affecting wagtail customizations
  - [ ] [Changes to submissionslistview class](https://docs.wagtail.org/en/latest/releases/6.1.html#changes-to-submissionslistview-class)
  - [ ] [Register_user_listing_buttons hook signature changed](https://docs.wagtail.org/en/latest/releases/6.1.html#register-user-listing-buttons-hook-signature-changed)
  - [ ] [Password_required_template has changed to wagtail_password_required_template](https://docs.wagtail.org/en/latest/releases/6.1.html#password-required-template-has-changed-to-wagtail-password-required-template)
  - [ ] [Document_password_required_template has changed to wagtaildocs_password_required_template](https://docs.wagtail.org/en/latest/releases/6.1.html#document-password-required-template-has-changed-to-wagtaildocs-password-required-template)
### Changes to undocumented internals
  - [ ] [Deprecation of user_listing_buttons template tag](https://docs.wagtail.org/en/latest/releases/6.1.html#deprecation-of-user-listing-buttons-template-tag)
  - [ ] [Deprecation of wagtailusers_groups:users url pattern](https://docs.wagtail.org/en/latest/releases/6.1.html#deprecation-of-wagtailusers-groups-users-url-pattern)
  - [ ] [Deprecation of window.chooserurls within draftail choosers](https://docs.wagtail.org/en/latest/releases/6.1.html#deprecation-of-window-chooserurls-within-draftail-choosers)
  - [ ] [Deprecation of window.initblockwidget to initialize a streamfield block](https://docs.wagtail.org/en/latest/releases/6.1.html#deprecation-of-window-initblockwidget-to-initialize-a-streamfield-block)
  - [ ] [Old](https://docs.wagtail.org/en/latest/releases/6.1.html#id1)
  - [ ] [New](https://docs.wagtail.org/en/latest/releases/6.1.html#id2)
  - [ ] [Removal of jquery from base client-side widget and boundwidget classes](https://docs.wagtail.org/en/latest/releases/6.1.html#removal-of-jquery-from-base-client-side-widget-and-boundwidget-classes)
  - [ ] [Window.urlify deprecated](https://docs.wagtail.org/en/latest/releases/6.1.html#window-urlify-deprecated)
  - [ ] [Window.xregexp polyfill removed](https://docs.wagtail.org/en/latest/releases/6.1.html#window-xregexp-polyfill-removed)

2024-05-16 08:43 UTC, katdom13 commented
I had to bump the minimum Wagtail version to 5.2 since older ones have reached EOL. Same for the Django versions

2024-05-17 10:43 UTC, nickmoreton requested changes
Hi @katdom13 This all looks good. Just one update looks like is needed on the Makefile

https://github.com/torchbox-forks/wagtail-django-recaptcha/blob/81fa9f90e77cdcde491c2d463193f67892d07a9d/Makefile#L29

I noticed that running the `update-test-fixture` command failed and it was because the fixtures file is in a different location in the home app.

Also the fixtures end up with data that's new in wagtail but isn't excluded.

This should help with modernising it.

```
update-test-fixture: ## Update test fixture from the db.
	python ./tests/testapp/manage.py dumpdata --indent=4 \
	-e contenttypes -e auth.permission -e auth.group -e sessions \
	-e wagtailcore.site -e wagtailcore.revision -e wagtailcore.grouppagepermission \
	-e wagtailimages.rendition -e wagtailcore.collection -e wagtailcore.groupcollectionpermission \
	-e wagtailcore.locale \
	-e wagtailcore.workflowpage -e wagtailcore.workflowtask -e wagtailcore.task -e wagtailcore.workflow -e wagtailcore.groupapprovaltask \
	> tests/testapp/home/fixtures/test_data.json
```

2024-05-17 12:06 UTC, katdom13 commented
> Hi @katdom13 This all looks good. Just one update looks like is needed on the Makefile
> 
> https://github.com/torchbox-forks/wagtail-django-recaptcha/blob/81fa9f90e77cdcde491c2d463193f67892d07a9d/Makefile#L29
> 
> I noticed that running the `update-test-fixture` command failed and it was because the fixtures file is in a different location in the home app.
> 
> Also the fixtures end up with data that's new in wagtail but isn't excluded.
> 
> This should help with modernising it.
> 
> ```
> update-test-fixture: ## Update test fixture from the db.
> 	python ./tests/testapp/manage.py dumpdata --indent=4 \
> 	-e contenttypes -e auth.permission -e auth.group -e sessions \
> 	-e wagtailcore.site -e wagtailcore.revision -e wagtailcore.grouppagepermission \
> 	-e wagtailimages.rendition -e wagtailcore.collection -e wagtailcore.groupcollectionpermission \
> 	-e wagtailcore.locale \
> 	-e wagtailcore.workflowpage -e wagtailcore.workflowtask -e wagtailcore.task -e wagtailcore.workflow -e wagtailcore.groupapprovaltask \
> 	> tests/testapp/home/fixtures/test_data.json
> ```

HI @nickmoreton ,
Applied suggestion here:
https://github.com/torchbox-forks/wagtail-django-recaptcha/pull/17/commits/dcf18c2cdd59e20ac233b5d551eb215e6582620a

Thanks for the suggestion! Where did you get it?

2024-05-17 12:55 UTC, nickmoreton commented
> Thanks for the suggestion! Where did you get it?

HI @katdom13 Mostly from experience but I new about this here: https://docs.wagtail.org/en/v6.1/advanced_topics/testing.html#fixtures which leads you onto the Django docs.
When I fixed the folder for the dump file I noticed the differences between the original dump file and the new one and thought we wouldn't need the extra data I could see so excluded them until it matched what was in the old one.

2024-05-17 12:57 UTC, nickmoreton approved these changes
👍

2024-05-20 04:25 UTC, merged